# Generated by Django 4.1.6 on 2023-02-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kundalik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaqti', models.DateTimeField()),
                ('izoh', models.TextField()),
                ('maqsad', models.CharField(max_length=60)),
            ],
        ),
    ]
